server:
  port: 9093
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Mysql@143
    url: jdbc:mysql://localhost:3306/NewDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update